p4-tools-pdiffvw: Add -d (diff'ing all files underneath a directory)

diff --git a/p4/tools/pdiffvw b/p4/tools/pdiffvw
--- a/p4/tools/pdiffvw
+++ b/p4/tools/pdiffvw
@@ -5,8 +5,53 @@ usage() {
 	echo "options:"
 	echo "       -f <filename>: display diff of a particular file"
 	echo "       -F <flist>: file containing list of files to be diff'd"
+	echo "       -d <dir>: directory to be diff'd"
 	echo "       -o <outfile>: output file where diff will be stored (default stdout)"
 	exit 1
+}
+
+pdiffvw_all() {
+	if [ -n "${outfile}" ]; then
+		p4 diff -du > ${outfile}
+	else
+		p4 diff -du | less
+	fi
+}
+
+pdiffvw_file() {
+	local filename=$1
+
+	if [ -n "${outfile}" ]; then
+		p4 diff -du ${filename} > ${outfile}
+	else
+		p4 diff -du ${filename} | less
+	fi
+}
+
+pdiffvw_files() {
+	local files="$1"
+
+	for f in ${files}; do
+		pdiffvw_file ${f}
+	done
+}
+
+pdiffvw_flist() {
+	local flist=$1
+
+	if [ ! -f ${flist} ]; then
+		echo "${progname}: missing ${flist}"
+		exit 1
+	fi
+	files="`cat ${flist}`"
+	pdiffvw_files "${files}"
+}
+
+pdiffvw_dir() {
+	dir=$1
+	files_dir="`p4 opened | awk '{print $1}' | awk -Fdepot '{print $2}' | awk -F'#' '{print $1}' | awk -F${branch}/ '{print $2}' | grep ${dir}`"
+	pdiffvw_files "${files_dir}"
+
 }
 
 progname=`basename $0`
@@ -18,7 +63,8 @@ fi
 filename=
 flist=
 outfile=
-while getopts ":hf:F:o:" arg; do
+dir=
+while getopts ":hf:F:o:d:" arg; do
 	case $arg in
 	f)	filename=${OPTARG}
 		;;
@@ -26,10 +72,14 @@ while getopts ":hf:F:o:" arg; do
 		;;
 	o)	outfile=${OPTARG}
 		;;
+	d)	dir=${OPTARG}
+		;;
 	*)	usage
 		;;
 	esac
 done
+
+branch=`adu mappings | tail -2 | grep -v ^$ | awk '{print $1}' | awk -F/ '{print $NF}'`
 
 if [ -n "${outfile}" ]; then
 	out_dirname=`dirname ${outfile}`
@@ -37,30 +87,13 @@ if [ -n "${outfile}" ]; then
 fi
 
 if [ -n "${filename}" ]; then
-	if [ -n "${outfile}" ]; then
-		p4 diff -du ${filename} > ${outfile}
-	else
-		p4 diff -du ${filename} | less
-	fi
+	pdiffvw_file ${filename}
 elif [ -n "${flist}" ]; then
-	if [ ! -f ${flist} ]; then
-		echo "${progname}: missing ${flist}"
-		exit 1
-	fi
-	files="`cat ${flist}`"
-	for f in ${files}; do
-		if [ -n "${outfile}" ]; then
-			p4 diff -du ${f} >> ${outfile}
-		else
-			p4 diff -du ${f} | less
-		fi
-	done
+	pdiffvw_flist ${flist}
+elif [ -n "${dir}" ]; then
+	pdiffvw_dir ${dir}
 else
-	if [ -n "${outfile}" ]; then
-		p4 diff -du > ${outfile}
-	else
-		p4 diff -du | less
-	fi
+	pdiffvw_all
 fi
 exit 0
 
