aos-tools-sos-crash-tech-support: Add seatbelts to ensure gdbscripts_dir is a valid path before progressing.

diff --git a/aos/tools/sos-crash-tech-support b/aos/tools/sos-crash-tech-support
--- a/aos/tools/sos-crash-tech-support
+++ b/aos/tools/sos-crash-tech-support
@@ -235,6 +235,10 @@ if [ -n "${GDBSCRIPTS_CLIENT}" ]; then
 else
 	gdbscripts_dir=${P4CLIENT_DIR}/sos/gdbscripts
 fi
+if [ ! -d ${gdbscripts_dir} ]; then
+	echo "${progname}: ${gdbscripts_dir} not found"
+	exit 1
+fi
 
 AOS_TOOLS_DEF=/usr/local/aos/tools
 AOS_TOOLS=${AOS_TOOLS_DIR:-${AOS_TOOLS_DEF}}
